### ISSUE TITLE
Generated executable -debug option conflict

### ISSUE THREAD

**Issue by norrisgc** [MScholtes/TechNet-Gallery#10]
The generated executable is given a -debug option. This conflicts with the -debug common parameter. A different name should be used for this option in the generated executable: I suggest -callbreak, which is also more descriptive.

**Comment by MScholtes** [comment]
Hello norrisgc,

you are obviously right. I will chnage this in the next version of **PS2EXE**.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello norrisgc,

I checked in the new version of **PS2EXE** today. It has the new parameter **_-prepareDebug_** instead of **_-debug_**, which prepares an generated executable for debugging (but the executable has to be called with **_-debug_** then).

It took quite a long time, as I hardly have any time on the computer (due to childcare) because of the Corona crisis. I apologise for this.

Greetings

Markus

**Comment by MScholtes** [comment]
Closing the issue, since it has been resolved and there is no reaction.
