### ISSUE TITLE
Please do not suggest that folks poison AV wells

### ISSUE THREAD

**Issue by sempervictus** [MScholtes/TechNet-Gallery#12]
Any tool which packages function into executables or provides a mechanism by which to run code is considered an execution harness in the security world (or just a compiler toolchain). Your psh2exe is not much different from my rex-powershell work (part of metasploit for a decade), and while neither piece of code is in itself malware, both can be used maliciously and are therefore signed-for in defensive tooling.
If the proposed effort to reduce the risk factor of PEs created this way as seen by the AV DBs is successful, it will make the harness _that much more appealing to malicious actors_. This is a real-life logic bug you just can't beat: technology is a two-edged sword and the "bad guys" are much more willing and able to use their edge than the average lazy non-security oriented "coder."
Please do not try to poison the wells of defensive tooling by crowd-sourcing benign sample submissions - you are not at fault for how your code is used in the wild, but you would be at fault for diminishing the defensive posture of organizations and people relying on those databases (potentially with actual liability attached, might want to check the ToS for those services).
Sometimes cool academic things such as this are just not practical in the real war-zone world because they are immediately weaponized and misused (relative to the author's intent). Maybe when people get civil, we can have nice things again.

**Comment by MScholtes** [comment]
Hello sempervictus,

I am sorry to tell you that I do not share your assessment at all. PS2EXE encodes the original Powershell script Base64 encoded. I expect AV vendors to recognise this, decode the code and only raise an alarm if the script it contains poses a threat. For this reason, it makes sense to send in harmless examples.

I also cannot stand the self-righteousness of security specialists, instead of making the computer world safer, they deliver tools that invite abuse and then talk it up.

Since this is not an issue, I am closing it.

Greetings

Markus
